### ISSUE TITLE
名寄せできそうな人の報告です

### ISSUE THREAD

**Issue by ledsun** [ima1zumi/RubyKaigi-speakers#2]
## 青木 峰郎さん

- 2007 Minero Aoki
- 2008 Minero AOKI

## 須藤 功平さん

- 2006 須藤功平
- 2007 Sutou Kouhei

## 大場 光一郎さん

- 2008 Koichiro OHBA
- 2011 Koichiro Ohba

## ujihisaさん

- 2008 ujihisa
- 2009 Tatsuhiro UJIHISA
- 2019 Tatsuhiro Ujihisa

## 松本 宗太郎さん

- 2008 Soutaro MATSUMOTO
- 2017 Soutaro Matsumoto

## remoreさん

- 2014 Kei Sawada
- 2024 Kay Sawada

**Comment by ima1zumi** [comment]
ありがとうございました！
